name: Build and Test

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Start project
        run: npm run dev &

      - name: Wait for the server to be ready
        run: wait-on http://localhost:3000

      - name: Clone test Cypress repository
        run: git clone https://github.com/rafaellopezsouza/portifolio-cypress-ts

      - name: Install Cypress dependencies
        run: |
          cd portifolio-cypress-ts
          npm install

      - name: Run Cypress tests in dev environment
        run: |
          cd portifolio-cypress-ts
          npm run dev:cy
